### ISSUE TITLE
Server can`t start

### ISSUE THREAD

**Issue by WangBeishan** [AykutSarac/chatify#3]
Hi, When I use to start project, an error occurred. as follows:
chatify/src/server/controllers/messages.js:58 .then((res) => res.data?.users.map((id) => 'id=' + id));
When I delete '?' Rear, server not start
A 500 error is thrown when sending post and other requests.
Hope to receive your reply, Thanks

**Comment by AykutSarac** [comment]
Did you do changes at `db.json` previously? I suggest changing yours with chatify's default db file.

**Comment by AykutSarac** [comment]
Closing issue as further information is not provided.
